# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("QMainWindow")
        MainWindow.resize(499, 401)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(90, 90, 371, 41))
        self.txtInput.setObjectName("txtInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txtRails = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtRails.setGeometry(QtCore.QRect(90, 150, 104, 31))
        self.txtRails.setObjectName("txtRails")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(40, 220, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(160, 220, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.label_5.setObjectName("label_5")
        self.txtOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(90, 270, 371, 41))
        self.txtOutput.setObjectName("txtOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MÃ HOÁ VÀ GIẢI MÃ RAIL FENCE CIPHER"))
        self.label_3.setText(_translate("MainWindow", "nhập văn bản:"))
        self.label_4.setText(_translate("MainWindow", "số rail:"))
        self.btnEncrypt.setText(_translate("MainWindow", "encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "decrypt"))
        self.label_5.setText(_translate("MainWindow", "kết quả:"))
